clearvars -except ...
    'dataDirectory'...
    'datasetName'...
    'regressorName'...
    'dataset'...
    'regressor'...
    'robotSpeed'...
    'areaOfInterest'...
    'regressorFeatures'...
    'regressorLabels'...
    'featureNames';
