disp(['Saving data to',dataDirectory,datasetName, '...']);

% save it in the data folder
save(strcat(dataDirectory,datasetName), ...
    'robotSpeed',...
    'areaOfInterest', ...
    'dataset');

if exist('regressor', 'var')
    save(strcat(dataDirectory,regressorName), ...
        'regressor');
end