% ========== Estimating Feature Importance
regressor = TreeBagger(regressionInfo.nbOfTrees,...
    regressionInfo.trainingFeatures,regressionInfo.trainingLabels,...
    'Method','R',...
    'OOBVarImp','On',...
    'MinLeaf',regressionInfo.nbOfLeaves);

regressionInfo.featuresImportance = regressor.OOBPermutedVarDeltaError;
