disp('Training the regressor...');

regressor = TreeBagger(...
    regressionInfo.nbOfTrees,...
    regressionInfo.features, regressionInfo.labels,...
    'Method', 'R',...
    'MinLeaf', regressionInfo.nbOfLeaves);