regressor = TreeBagger(...
    nbOfTrees,...
    dataset, labels,...
    'Method', 'R',...
    'MinLeaf', nbOfLeaves);

% To get more information after, train with:
%     'OOBPred', 'On',...
%     'OOBVarImp','On',...