nbOfTrees = 500; % More you have better result are (with longer processing)
nbOfLeaves = 5; % Selected from data analysis

regressor = TreeBagger(...
    nbOfTrees,...
    dataset, labels,...
    'Method', 'R',...
    'MinLeaf', nbOfLeaves);

% To get more information after, train with:
%     'OOBPred', 'On',...
%     'OOBVarImp','On',...