dataDirectory = './data/';

datasetStruct = struct(...
    'name', '',...
    'rawCurrents', [],...
    'traversabilityStartIndex', [],...
    'traversabilityStopIndex', [],...
    'traversabilityCost', [],...
    'rawPointCloud', [],...
    'areaOfInterest', [],...
    'image', []);

robotSpeed = 0.3; % m/s
areaOfInterest = struct(...
    'distFromRobot', 2.0,...
    'depth', 1.6,...
    'width', 0.8,...
    'height', 1.5);

