dataDirectory = '../Data/';

robotSpeed = 0.3; % m/s

areaOfInterest = struct(...
    'distFromRobot', 2.0,...
    'depth', 1.6,...
    'width', 0.8,...
    'height', 1.5,...
    'groundThreshold', 0.12); % Lower than half wheel and robot body (12 cm)

datasetStruct = struct(...
    'name', '',...
    'rawCurrents', [],...
    'traversabilityStartIndex', [],...
    'traversabilityStopIndex', [],...
    'traversabilityCost', [],...
    'rawPointCloud', [],...
    'groundHeight', [],...
    'areaOfInterest', [],...
    'image', [],...
    'features', containers.Map);



