clc;
clearvars -except 'justRunAll';
close all;
clc;
addpath(genpath('.'));

% ========== Define global variables and data structures ==============
dataDirectory = '../../WoodlandNavigationData/RegressionV2/';
%     slopeCorrectionFile = '../Data/SlopeCorrection/slopeCorrection.mat';
%     load(slopeCorrectionFile);

dataset = []; % Variable to contain the dataset
regressor = []; % Variable to contain the regressor

robotSpeed = 0.3; % m/s
areaOfInterest = struct(...
    'distFromRobot', 1.0,...
    'depth', 2.6,...
    'width', 1.0,...
    'height', 1.4,...
    'xTfAdjustment', 0.00,... % base_link + adjust = body front
    'groundThreshold', 0.12); % Lower than half wheel and robot body

imuDftParams = struct(...
    'usedIMU', 2,... % 2-4 inertia, 5-7 angular, all: 2:7
    'isFirstIndexRemoved', true,...
    'endFractionRemoved', 1/2,...
    'nbOfColumnsMerged', 1,...
    'areVectorsNormalized', false,...
    'areFeaturesNormalized', false,...
    'isMatrixWhiten', false);

traversabilityCostInfo = struct(...
    'wantToCorrectSlope', false,...
    'motorCurrentsIntegralMetric', 1,...
    'motorCurrentsVarianceMetric', 2,...
    'inertiaVarianceMetric', 3,...
    'odometryErrorMetric', 4,...
    'imuDftMinkowski1FromOrigin', 5,...
    'imuDftMinkowski2FromOrigin', 6,...
    'randomValueMetric', 7,...
    'traversabilityMetrics', 5);

datasetStruct = struct(...
    'name', '',...
    'rawCurrents', [],...
    'dftCurrents', [],...
    'rawIMU', [],...
    'dftIMU', [],...
    'rollPitchYaw', [],...
    'icpOdometry', [],...
    'traversabilityStartTime', [],...
    'traversabilityStopTime', [],...
    'traversabilityCost', [],...
    'userTraversabilityCost', [],...
    'rawPointCloud', [],...
    'groundHeight', [],...
    'areaOfInterest', [],...
    'image', [],...
    'features', containers.Map);
regressionInfo = struct(...
    'featureNames', [],...
    'featuresImportance', [],...
    'trainingFeatures', [],...
    'trainingLabels', [],...
    'testFeatures', [],...
    'testLabels', [],...
    'nbOfTrees', 500,...
    'nbOfLeaves', 5);
evaluationStruct = struct(...
    'name', [],...
    'labels', [],...
    'meanSquaredError', [],...
    'rSquared', []);
evaluations = []; % To store all leave one out results
